### ISSUE TITLE
Codemirror v6 support?

### ISSUE THREAD

**Issue by siefkenj** [qualified/lsps#109]
This project looks really great! Are there any plans to integrate CodeMirror v6 support?

**Comment by kazk** [comment]
No, there's no plan to make this support CodeMirror v6 because the APIs are incompatible. It's probably easier to create a new project instead. We're also not using CM6 in any of our products currently, so there's no plan for the new package.

I'm not sure if there are packages supporting multiple editors like ours, but I've seen a few packages providing Language Server support for CM6, so you might want to check them out.
